select
COUNTRY.CTRY_ID,
COUNTRY.AREA,
COUNTRY.CONT_ID,
COUNTRY.CURRENCY,
COUNTRY.CTRY_NAME,
COUNTRY.POP,
COUNTRY.POP_UPD_ON
from
COUNTRY,
CONTINENT
where
COUNTRY.CONT_ID=CONTINENT.CONT_ID
and CONT_NAME='Africa'